# Generated by Django 3.1.3 on 2020-12-21 10:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_1',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='preview_2',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='preview_3',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
